export const CityActionTypes = {
  GET_ALL_CITIES: "GET_ALL_CITIES",
  FETCHING_CITIES: "FETCHING_CITIES",
  GET_CITY_FROM_STORE: "GET_CITY_FROM_STORE"
};

export const ItineraryActionTypes = {
  GET_ALL_ITINERARIES: "GET_ALL_ITINERARIES",
  FETCHING_ITINERARIES: "FETCHING_ITINERARIES"
};
